@startuml

object User {
+input values
 }

object Menu {
+Start
}
object CallMenu{
+return
}
Object Terminate{
+message
}

map "Shapes<Integer, String>" as Shapes {
1 => Pyramid
2 => Sphere
3 => Cylinder
4 => Cone
5 => Rectangular Tank
6 => Cube
... => ........
}
object Formulas {
+Volume
+Surface Area

}
object Output {
+Volume
+Area
}
User --> Menu
Menu --> Shapes
Formulas --> Shapes
Shapes --> Output
Output --> Menu
Terminate <-- Menu
Menu <--> CallMenu



@enduml
